fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.20.0
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat.git
      ref: 2.2.1
    vcsrepo:
      repo: https://github.com/puppetlabs/puppetlabs-vcsrepo.git
    apache:
      repo: https://github.com/puppetlabs/puppetlabs-apache.git
      ref: 1.11.0
    sudo:
      repo: https://github.com/saz/puppet-sudo.git
#    yamlfile:
#      repo: https://github.com/reidmv/puppet-module-yamlfile.git
#    filemapper:
#      repo: https://github.com/voxpupuli/puppet-filemapper
    httpauth:
      repo: https://github.com/jamtur01/jamtur01-httpauth.git
    augeasproviders_core:
      repo: git://github.com/hercules-team/augeasproviders_core.git
    augeasproviders_shellvar:
      repo: git://github.com/hercules-team/augeasproviders_shellvar.git
    systemd:
      repo: https://github.com/camptocamp/puppet-systemd.git
  symlinks:
    openondemand: "#{source_dir}"
