fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.25.0
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
    subscription_manager:
      repo: https://github.com/waveclaw/puppet-subscription_manager.git
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat.git
    vcsrepo:
      repo: https://github.com/puppetlabs/puppetlabs-vcsrepo.git
    apache:
      repo: https://github.com/puppetlabs/puppetlabs-apache.git
      ref: v5.0.0
    sudo:
      repo: https://github.com/saz/puppet-sudo.git
    httpauth:
      repo: https://github.com/jamtur01/jamtur01-httpauth.git
    augeasproviders_core:
      repo: git://github.com/hercules-team/augeasproviders_core.git
    augeasproviders_shellvar:
      repo: git://github.com/hercules-team/augeasproviders_shellvar.git
    systemd:
      repo: https://github.com/camptocamp/puppet-systemd.git
    logrotate:
      repo: https://github.com/voxpupuli/puppet-logrotate.git
    epel:
      repo: https://github.com/stahnma/puppet-module-epel.git
  symlinks:
    openondemand: "#{source_dir}"
