---
.travis.yml:
  docker_sets:
    - set: centos-7
      collection: puppet5
    - set: centos-7
      collection: puppet6
    - set: centos-8
      collection: puppet5
    - set: centos-8
      collection: puppet6
  user: osc
  secure: "WwdtEZW5XovkRLoy52SXw5VveZpLSS6WPlsv7S5VbC70LAbZnhAt8CogYHRlrdhgEmeuJMBXv8Vc34yOVgDEaBmKuixxsjCn8KufyNQ9s2jEJ7ohigxt0HUqEuLTR6EBtJ1BUx+elqjCgw4JmLGNXXXMe0z7LOzA5lBKWnkBNwCA2x3bdxni4/RHBekDafmgiYursndlpVyrWPhcWyHwEiaU+I3OBuY+nc5p5rNvEeRWeCov0Wotwh1t4dYbDc+daHTd6ovTMr+wbsv5FF5Ziwz25bakafUqiIwY//u/z8wrjGRq12yHXK0lm7XVfFl3iX7f9ktqe5XlutLCmtG9JsiC/ZvsAw66wQt6uvVpHsaDlFZNvxUbUOKzAZF4ycPEWIbxLmviSTbWA06TXf9Eb6az2aWyKpUInuCNGKas7Iy1i6CBzJZ6ttxayv1mTgmy4kWO94OX18MQSBotGLZ4xyRMzVsrt3yaMazYQBPFd/HMWhNqpu0VVFrM1s3+UYUzaIf8UOdgiXWwbEe3VA3cEcQ3aM20/bcSbWZCJvPNuDJwcZ0+jWBWW1CEHCeK0aILrs5MS7mZ881j8TakoE7U80API7YQuHYKHGeNZBxfBxdf7SL/Y4QuDWofQDApyZ4KRleaYC3zC497yVVmvfhx15SMP2VnpKGZD0xQHafRUuA="
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/debian-9.yml:
  delete: true
spec/acceptance/nodesets/debian-10.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1404.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
