---
.travis.yml:
  docker_sets:
    - set: centos-7
      collection: puppet5
    - set: centos-7
      collection: puppet6
    - set: centos-6
      collection: puppet5
    - set: centos-6
      collection: puppet6
  user: treydock
  secure: "K9RN7UJifVoI/4pxQwRz790Owtt2jnLXa8gtEx5RHqYxoMhBaKjYdDFXiYiWrSXpJcPkfMVWfuvC+72sOa76FNaT+RJiWY3CKt8xB1OcLVq/ZBJDDBz22P6mz+w0o2RyIyBQnYKvjwiw5/jgFkoW2XEbDn7+P2u4TrbX0iK9F0BUJNTQIbo7D5/2obpD90tuO/YnZOOmpTjk6R9TJML+n64Vz5tX4Qx9bmE9fitMa7r/cyc54d/iuu/zkkO6c2XiG13ftbh4/PapVGFT/krRjxQhvihfa9/sM1gRIUSBaRd6X09S+5A9rpRMl/Jxhbx+ZvB0JR8ofyj8nKeyH1ECXD1RSBO95Wse+heu5tCKaPZsAek6XhF45nFT7pM/uBXep2vr43Qv2QDTuCbr1+mWFDvUgY+xf/SRneGDmBVGTAQ4QjVC7Y2M0hRb7iwNrhqd0Fg5Y/dA9/xnvQdiz7W9GiQG2eGBYSqrz7hJLLoxuiKLMPPzWE3uo0MrhmBb2/hwUFXXjqDnZBtvYc9oP7QalZbcAyLRaROSiciBb7KUOU1Up4FdYuJ5GkGjPfLBLc1CohWNRivbOcqrmjTshevAygHrlixLP9mlTOJP7Ped+yakdiGuEge1Mix/xuIMG6SQZUavKjx/NgqB0IQ7Nr9EJA6++W6zf9jZ2C4B990HriQ="
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/debian-9.yml:
  delete: true
spec/acceptance/nodesets/debian-10.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1404.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
