---
.travis.yml:
  docker_sets:
    - set: centos-7
      collection: puppet5
    - set: centos-7
      collection: puppet6
    - set: centos-8
      collection: puppet5
    - set: centos-8
      collection: puppet6
  user: osc
  secure: "OcbsSaxA6+mZ6GFo+C4c0c9o1h+bNXg0EJ8GsWS6ZNJHBbu0AeBB9v4ctWIDbk0n7GCijYEXNAgZtWy4ZN3dYbDqgw8z7gvcoJGtEvjdDPUD29+EIIJctx68wxLf3cm9nBeJStnHb2krU4NaVn8lty6pMoRoT0qDTwWeoF6BZVC0nR6qVYEG8Vh89snvr2LXel3XQS4BEeEIOh2/sLghRiON1jOvWTsTzI0LtF3PZsKXkkUDHPAFzeuZ5Txf+MZkIpdxZYjEcPssJLMS/JgykGkCfpcCy1lOOZrzGAQ/XelxbL6Lhzp8l4vcSkwPqggkeKFStHJzNCRaOR4mvplz9K2P4AarnVb87H9qqvYlnQgW8/oBDt1e8t/ociB8KUvLRWh5GSkUbghNQeWl2oQHj8ACgwCpQ6FXwY3iV1ONTD3ZRvsE9zgVeG2zH79y9pqORgOSEoy3NKfp2Dwdusf/UzW3yUI1uyUE3rYr8Jp8TPqrewm3erpXRU8INZcwqEMZLctHbCTHSOqz/FPyElJfPv78bDc7GmtyBxcMmvghL1GfryLklf5pR5r7du2D8fHvmmtskkVmBSg2yZFEidTyAohKXcZj0evdCrfGI06yKkdkhqTcrCFP8UWUQGZg2C+ghSPdhxKXE49Cz4RWsywh/4xlAfyCxlytCbl1oliPbqU="
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/debian-9.yml:
  delete: true
spec/acceptance/nodesets/debian-10.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1404.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
