---
.travis.yml:
  docker_sets:
    - set: centos-7
      collection: puppet5
    - set: centos-7
      collection: puppet6
    - set: centos-6
      collection: puppet5
    - set: centos-6
      collection: puppet6
  user: treydock
  secure: "PmM0bTvtK7ulgWCNVs8/i9+A+nYfTiOKoA1Ip2fI2aEKyOnigbVBnKbplPEy15/zazEpY35qaPHMMJROnPsrl+KAJwhDVhMPigq8dPiIE/D/TpZSYNU6aWeaGQFxLp5WV46ozvI7/cDEEFK6nmeCNhjFb108b0i7yGxWu+blQm/3mBMVVGS/Om/p59eqfmmfnnasJ3iwW8IKI9cOoIYJK7xi1XZ96sXg1UNrmjKfMExeCOtZbPBjL1Fmn1d7Vzouri4R+p+XyAsRo21/sOChi6zq41B/+ABVl3KxB+eSlQ/qQnLmAc9gZJr0xxfK1EmtmZmw/9JnB5IiTO/XRJvlIUiHuxLpQ+NAAwaGkMQzJ8xNvozlr8bo9nk2kyssmJLogBmQwHLuOxDiPp9fg8hypgOgayitlYoHrBwel+tBr+39aY/Uxy2+oqI0SLt1RSJ/OmUQxFyeChBsArGEYrN0uuZofMMSi99SrtM7C627fbhqOYujJGOrEVKwGWF4jVpQpwdRauNtDGw4jrqnd6JPObgFB4oZVsOFaN1PaGU6GCtqbfMr3+326Afo8VmniY9K9BrwygT0ObkseWyb1ahi4D8a7WSOl4123n619klo2QK0994aPQ/ChIBWXya8A+9u3jSYgsFtWUM7xq1sD13/PgJuh4DSu3NE0lrUrK5LHcg="
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/debian-9.yml:
  delete: true
spec/acceptance/nodesets/debian-10.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1404.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
