---
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=centos-7 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=centos-7 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=centos-6 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=centos-6 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: treydock@gmail.com
deploy:
  provider: puppetforge
  user: osc
  password:
    secure: "OcbsSaxA6+mZ6GFo+C4c0c9o1h+bNXg0EJ8GsWS6ZNJHBbu0AeBB9v4ctWIDbk0n7GCijYEXNAgZtWy4ZN3dYbDqgw8z7gvcoJGtEvjdDPUD29+EIIJctx68wxLf3cm9nBeJStnHb2krU4NaVn8lty6pMoRoT0qDTwWeoF6BZVC0nR6qVYEG8Vh89snvr2LXel3XQS4BEeEIOh2/sLghRiON1jOvWTsTzI0LtF3PZsKXkkUDHPAFzeuZ5Txf+MZkIpdxZYjEcPssJLMS/JgykGkCfpcCy1lOOZrzGAQ/XelxbL6Lhzp8l4vcSkwPqggkeKFStHJzNCRaOR4mvplz9K2P4AarnVb87H9qqvYlnQgW8/oBDt1e8t/ociB8KUvLRWh5GSkUbghNQeWl2oQHj8ACgwCpQ6FXwY3iV1ONTD3ZRvsE9zgVeG2zH79y9pqORgOSEoy3NKfp2Dwdusf/UzW3yUI1uyUE3rYr8Jp8TPqrewm3erpXRU8INZcwqEMZLctHbCTHSOqz/FPyElJfPv78bDc7GmtyBxcMmvghL1GfryLklf5pR5r7du2D8fHvmmtskkVmBSg2yZFEidTyAohKXcZj0evdCrfGI06yKkdkhqTcrCFP8UWUQGZg2C+ghSPdhxKXE49Cz4RWsywh/4xlAfyCxlytCbl1oliPbqU="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
